/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{js,jsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'inverse-on-surface': '#ce8c89',
        'secondary-container': '#9df197',
        'tertiary-container': '#fec330',
        'on-secondary': '#d1ffc8',
        'on-tertiary-fixed-variant': '#634900',
        'surface-tint': '#ac2c00',
        'on-tertiary-container': '#584000',
        'on-background': '#4e2120',
        'on-tertiary': '#fff1db',
        'on-primary-container': '#480d00',
        'primary-fixed': '#ff7852',
        'on-primary': '#ffefec',
        'surface-container-lowest': '#ffffff',
        'background': '#fff4f3',
        'secondary': '#176a21',
        'on-surface': '#4e2120',
        'outline': '#a26765',
        'error': '#b31b25',
        'error-container': '#fb5151',
        'surface-container-high': '#ffdad8',
        'on-error-container': '#570008',
        'tertiary-fixed-dim': '#efb520',
        'surface-variant': '#ffd2d0',
        'on-tertiary-fixed': '#402d00',
        'tertiary': '#765600',
        'primary-dim': '#972500',
        'on-surface-variant': '#834c4b',
        'tertiary-fixed': '#fec330',
        'secondary-dim': '#025d16',
        'on-primary-fixed-variant': '#581200',
        'surface-container': '#ffe1e0',
        'tertiary-dim': '#674b00',
        'surface-container-low': '#ffedeb',
        'on-primary-fixed': '#000000',
        'secondary-fixed-dim': '#90e28a',
        'primary': '#ac2c00',
        'inverse-primary': '#fb5b2d',
        'surface-container-highest': '#ffd2d0',
        'surface-dim': '#ffc7c4',
        'on-error': '#ffefee',
        'surface-bright': '#fff4f3',
        'error-dim': '#9f0519',
        'primary-container': '#ff7852',
        'outline-variant': '#e09c99',
        'primary-fixed-dim': '#fe5e2f',
        'surface': '#fff4f3',
        'secondary-fixed': '#9df197',
        'on-secondary-fixed-variant': '#12661e',
        'inverse-surface': '#240304',
        'on-secondary-container': '#005c15',
        'on-secondary-fixed': '#00460e',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '1.5rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Epilogue'],
        body: ['Plus Jakarta Sans'],
        label: ['Plus Jakarta Sans'],
      },
    },
  },
  plugins: [require('tailwindcss/plugin')],
}
